// V5.166: los textos del dossier CTCx, en español e inglés. Sin rayas largas ni emojis (la guía de diseño de la casa
// para documentos: una frase llana es mejor que una frase ingeniosa).
import { CTC_RAZON } from "@/lib/legal";
import type { Lang } from "@/lib/kaffetal/dossierDatos";

const ES = {
  doc: "Dossier del lote",
  otroIdioma: "English version",
  imprimir: "Imprimir o guardar PDF",
  generado: "Generado el",
  pagina: "Página",
  indice: "Contenido",
  secciones: { origen: "Origen", taza: "Perfil de taza", visa: "Visa EUDR", grado: "El grado", fisico: "Análisis físico", mejora: "Mejora", respaldo: "Respaldo" },
  // Portada
  grado: "Grado CTCx",
  sinGrado: "Sin grado todavía",
  puntos: "puntos CTCx",
  punto: "Punto SCA",
  origenDe: "Origen",
  altitud: "Altitud",
  variedad: "Variedad",
  proceso: "Proceso",
  cosecha: "Cosecha",
  referencia: "Referencia",
  fotoFinca: "Finca",
  // Origen
  origenTitulo: "De dónde viene este café",
  cafetales: "Cafetales del lote",
  ubicacion: "Ubicación",
  vertices: (n: number) => `Polígono de ${n} vértices`,
  puntoGeo: "Punto georreferenciado",
  area: "Área",
  vereda: "Vereda",
  municipio: "Municipio",
  departamento: "Departamento",
  pais: "País",
  sistema: "Sistema de producción",
  siembra: "Siembra",
  tenencia: "Tenencia",
  infraTitulo: "Beneficio e infraestructura",
  aporte: "Aporte al lote",
  escalaAltitud: "Altitud de la finca sobre el nivel del mar",
  productor: "Productor",
  historia: "La historia de la finca",
  caracteristicas: "Lo que la distingue",
  galeria: "Galería del productor",
  otrasFincas: "Otras fincas del lote",
  // Visa
  visaTitulo: "Visa EUDR del lote",
  visaLead: "La debida diligencia del Reglamento (UE) 2023/1115 vive en la finca. El lote hereda su Visa del Pasaporte EUDR de cada finca de origen, sin trámites propios.",
  visaEstado: { eudr_ready: "Visa vigente", pendiente: "Visa en trámite", bloqueado: "Visa retenida", sin_origen: "Sin origen declarado" } as Record<string, string>,
  pasaporteEstado: { apta: "Pasaporte vigente", aprobada: "Aprobado, expediente sin remitir", en_revision: "En revisión por CTCx", pendiente: "En trámite", rechazada: "Rechazado", no_apta: "Sin Pasaporte" } as Record<string, string>,
  cadena: { finca: "Finca", fincaSub: "Pasaporte EUDR", lote: "Lote", loteSub: "Visa heredada", dds: "Exportación", ddsSub: "Declaración DDS", ue: "Comprador UE", ueSub: "Verifica la referencia" },
  criteriosTitulo: "Lo que acredita el Pasaporte de la finca",
  criterio: {
    deforestacion: "Libre de deforestación después del 31/12/2020",
    legal: "Producción conforme a la legislación del país",
    tenencia: "Tenencia de la tierra declarada",
    geo: "Geolocalización del predio",
    ilegalidad: "Sin indicios de ilegalidad",
    documentos: "Documentos disponibles y verificables",
    revision: "Expediente revisado por CTCx",
  },
  geoPoligono: (n: number) => `polígono de ${n} vértices`,
  geoPunto: "punto georreferenciado",
  sinRemitir: "aprobado, sin remitir",
  tenenciaLabel: { propietario: "Propietario", poseedor: "Poseedor reconocido", asociacion: "Asociación" } as Record<string, string>,
  estadoCriterio: { ok: "Cumple", pend: "Pendiente", stop: "No cumple" },
  riesgoPais: "Riesgo del país",
  riesgoPaisNota: "Clasificación de la Comisión Europea, Reglamento de Ejecución (UE) 2025/1093.",
  dds: "Declaración de diligencia debida (DDS)",
  ddsVerificacion: "verificación",
  sinDds: "La DDS la presenta el operador que importa el café; su referencia se anota aquí cuando exista.",
  sellos: "Sellos con cobertura total del lote",
  verificado: "verificado por CTCx",
  declarado: "declarado",
  sinSellos: "Ningún sello cubre el 100 % del lote todavía.",
  verVisa: "Ver la Visa EUDR completa",
  verPasaporte: (n: string, c: string) => `Ver el Pasaporte EUDR de ${n} (${c})`,
  geoTitulo: "Geolocalización del predio",
  geoLead: "Coordenadas WGS84 de los vértices del polígono declarado (Art. 9 del Reglamento). El operador europeo las usa en su declaración de diligencia debida.",
  geoPuntoLead: "Coordenadas WGS84 del punto georreferenciado del predio (Art. 9 del Reglamento; un predio de hasta 4 ha puede declararse con un punto).",
  vertice: "Vértice",
  latitud: "Latitud",
  longitud: "Longitud",
  masVertices: (n: number) => `y ${n} vértices más en el expediente de la finca`,
  // Grado
  gradoTitulo: "El Punto y la Tríada",
  gradoLead: "El grado CTCx combina la calidad en taza (el Punto SCA del Q-Grader) con tres atributos del lote: variedad, proceso y reconocimiento. Cada atributo sube el multiplicador según su nivel C, B o A.",
  // V5.189: el CVA es el protocolo principal; un SCA 2004 vale lo mismo por la equivalencia.
  puntoCva: "Punto CVA (SCA-104)",
  puntoSca2004: "Punto SCA 2004 (vale lo mismo en CVA)",
  multiplicador: "Multiplicador",
  total: "Puntos CTCx",
  triada: { variedad: "Variedad", proceso: "Proceso", reconocimiento: "Reconocimiento" },
  niveles: {
    variedad: { C: "Regional o tradicional", B: "Especial o híbrida", A: "Exótica o rara" },
    proceso: { C: "Lavado", B: "Honey, natural, infusiones", A: "Experimental, fermentaciones" },
    reconocimiento: { C: "Ninguno", B: "1 a 3", A: "4 o más" },
  },
  composicion: "Composición varietal declarada",
  escalaTitulo: "Dónde cae el lote en la escala CTCx",
  tituloTriada: "La tríada del lote",
  imagenDefecto: "Fincas y lotes de origen respaldado, ilustración de CTCx",
  variedadesTitulo: "Las variedades del lote",
  variedadesFuente: "Fichas del Mapa de Variedades de CTCx",
  sinFichaVariedad: (n: string) => `El Mapa de Variedades todavía no tiene una ficha para «${n}».`,
  grupoGenetico: "Grupo genético",
  origenVariedad: "Origen",
  altitudVariedad: "Altitud en que se da",
  granoVariedad: "Grano",
  notasVariedad: "Notas típicas en taza",
  sinEvaluacion: "El lote todavía no tiene una evaluación del Q-Grader que rija su grado. Esta página se completa cuando CTCx confirme el informe del Centro de Calidad.",
  // Taza
  tazaTitulo: "Perfil de taza",
  tazaLead: "La planilla del Q-Grader que rige el grado: la evaluación afectiva (cuánto agrada cada atributo) y la descriptiva (qué se percibe, dónde y con qué intensidad).",
  // V5.197 (owner): la telaraña de 8 esquinas del CVA y la descriptiva con íconos e intensidad.
  afectiva: "Evaluación afectiva",
  afectivaCva: "CVA · ocho atributos en la escala de 1 a 9",
  afectivaSca: "SCA 2004 · diez atributos en la escala de 6 a 10",
  afectivaFicha: "Atributos reportados en la Ficha del lote",
  escalaCva: "De 1 (extremadamente baja) a 9 (extremadamente alta). La línea punteada es el 5: ni alta ni baja.",
  radarCva: "Telaraña de los ocho atributos del CVA",
  puntoRige: "El Punto que rige el grado",
  esElPunto: "Es el Punto que rige el grado",
  tazasCva: (n: number, u: number, d: number) => `${n} tazas · ${u} no ${u === 1 ? "uniforme" : "uniformes"} · ${d} ${d === 1 ? "defectuosa" : "defectuosas"}`,
  comparativo: (protocolo: string, v: string) => `${protocolo} catado al lado: ${v}`,
  descriptiva: "Evaluación descriptiva",
  descriptivaLead: "Intensidad de 0 a 15: baja por debajo de 5, media de 5 a 9,5 y alta desde 10.",
  acidez: "Acidez",
  boca: "Sensación en boca",
  acidezTipo: { dulce: ["Dulce", "jugosa, frutal, brillante"], seca: ["Seca", "herbal, a pasto, agria"] } as Record<"dulce" | "seca", [string, string]>,
  sinIntensidad: "Sin intensidad",
  notasTitulo: "Notas de la rueda del sabor",
  // V5.198 (owner): el Dossier público del CTCx Public Catalogue.
  docPublico: "Dossier público del lote",
  volverPortal: "Find my Lot",
  regionPie: "La región del lote. La ubicación exacta de la finca no se publica.",
  region: "Región",
  eudrListo: "Lista para EUDR: trazabilidad hasta la finca, según el Reglamento (UE) 2023/1115.",
  avisoPublico: `Expediente público del lote en el CTCx Public Catalogue. Lo produce ${CTC_RAZON} con lo que el productor registró en Kaffetal Regal y lo que CTCx contrastó; lo que CTCx no verificó no se afirma. Para comprarlo o pedir una muestra, escriba a CTCx en ctcexport.com.`,
  tazas: "Tazas",
  taint: "taint",
  fault: "fault",
  cvaTitulo: "CVA (SCA-104)",
  rueda: "Notas en la rueda del sabor",
  ruedaFigura: "Dónde caen las notas en la rueda",
  ruedaFiguraNota: "Cada nota se dibuja en el ángulo de su familia y más lejos del centro cuanto más intensa. Borde rojo: nota de defecto.",
  intensidad: "intensidad",
  defectoNota: "nota de defecto",
  descriptivo: "Descriptivo",
  perfil: "Perfil del catador",
  totalSca: "Total SCA 2004",
  // Físico
  fisicoTitulo: "Análisis físico",
  fisicoLead: "Lo que pasa con una muestra de pergamino desde la trilla hasta el grano sano, y cómo se reparte el verde por tamaño.",
  rendimiento: "Rendimiento de la muestra",
  pergamino: "Pergamino",
  merma: "Merma de trilla",
  verde: "Verde trillado",
  defPrim: "Defecto primario",
  defSec: "Defecto secundario",
  sano: "Grano sano",
  factor: "Factor de rendimiento",
  factorNota: "kilos de pergamino por 70 kg de verde sano",
  humedad: "Humedad del verde",
  humedadRango: "rango de exportación 10 a 12 %",
  aw: "Actividad de agua",
  densidad: "Densidad",
  defectuosa: "Almendra defectuosa",
  mallas: "Granulometría",
  defectos: "Defectos físicos",
  defecto: "Defecto",
  granos: "Granos",
  completos: "Completos",
  noSabe: "No lo sabe",
  declaradoVsMedido: "Declarado por el productor y medido en laboratorio",
  declarado2: "Declarado",
  medido: "Medido",
  notasAnalisis: "Notas del análisis",
  // Mejora
  mejoraTitulo: "Mejora",
  respaldoHojaTitulo: "Respaldo",
  anot: "Anotaciones de mejora de la Rueda del Sabor",
  anotLead: "Las notas de defecto que marcó el Q-Grader y su causa más probable en el beneficio. Es lo primero que conviene revisar para la próxima cosecha.",
  anotLimpio: "La rueda del sabor no marcó notas de defecto: el perfil no muestra fallas de proceso.",
  causa: "Posible causa",
  lecturaTitulo: "Lectura del perfil",
  lecturaFuente: "Redactada como el reporte de la Rueda del Café, a partir de las notas que marcó el Q-Grader.",
  conjeturasTitulo: "Lo que sugieren las observaciones",
  conjeturasLead: "Hipótesis que se derivan de lo medido y lo declarado. Son puntos de partida para la próxima cosecha, no diagnósticos.",
  evidencia: "Sale de",
  areas: { taza: "Taza", fisico: "Físico", origen: "Origen" },
  respaldoTitulo: "Quién respalda cada dato",
  respaldoLead: "Cada bloque de este dossier y de dónde sale. Lleno: hecho. Punteado: pendiente. Raya: no aplica.",
  respaldoCols: ["Declaró el productor", "Revisó CTCx", "Midió el Q-Grader"],
  respaldoFilas: { finca: "Finca, mapa y altitud", visa: "Visa EUDR", triada: "Variedad, proceso y reconocimiento", taza: "Punto SCA y perfil de taza", fisico: "Análisis físico", grado: "Grado CTCx", certs: "Certificaciones" },
  certs: "Certificaciones de la finca corroboradas por CTCx",
  sinCerts: "Ninguna certificación corroborada todavía. Las declaradas sin respaldo no se imprimen.",
  esquema: "Esquema",
  numero: "N.º",
  vigencia: "Vigencia",
  catalogo: "Ficha pública del lote en el CTCx Public Catalogue",
  fuente: { q_grader_batch: "Evaluación CTCx por Q-Grader", bcp_arena: "Apreciación CTCx en la Arena", producer_claim: "Reportada por el productor y contrastada por CTCx" },
  fechaAnalisis: "Fecha del análisis",
  fichaFuente: { escaneo: "Soportes del productor transcritos por CTCx", productor: "Reportado por el productor", ctc: "Transcrita por CTCx" },
  aviso: `Este dossier lo produce ${CTC_RAZON} con la información que el productor registró en Kaffetal Regal y lo que CTCx contrastó. Lo que CTCx no verificó no se afirma.`,
  infra: {
    semillero: "Semillero", tractor: "Tractor", acopio: "Acopio", flotado: "Tanques de flotado", lavado: "Lavado", beneficio: "Beneficio especializado",
    fermentadores: "Fermentadores anaeróbicos", patios: "Patios de secado", marquesinas: "Marquesinas", guardiolas: "Guardiolas", silos: "Silos de secado",
    trilladora: "Trilladora", monitor_mallas: "Monitor de mallas", optica: "Seleccionadora óptica", vacio: "Empaque al vacío", tostadora: "Tostadora",
    molino: "Molino", empacadora_consumible: "Empacadora",
  } as Record<string, string>,
  sistemaLabel: { sombra: "Café bajo sombra", agroforestal: "Agroforestal", tradicional: "Tradicional a pleno sol" } as Record<string, string>,
};

type Textos = typeof ES;

const EN: Textos = {
  ...ES,
  doc: "Lot dossier",
  otroIdioma: "Versión en español",
  imprimir: "Print or save as PDF",
  generado: "Generated on",
  pagina: "Page",
  indice: "Contents",
  secciones: { origen: "Origin", taza: "Cup profile", visa: "EUDR Visa", grado: "The grade", fisico: "Physical analysis", mejora: "Improvement", respaldo: "Evidence" },
  grado: "CTCx Grade",
  sinGrado: "No grade yet",
  puntos: "CTCx points",
  punto: "SCA Point",
  origenDe: "Origin",
  altitud: "Altitude",
  variedad: "Variety",
  proceso: "Process",
  cosecha: "Harvest",
  referencia: "Reference",
  fotoFinca: "Farm",
  origenTitulo: "Where this coffee comes from",
  cafetales: "The lot's coffee plots",
  ubicacion: "Location",
  vertices: (n: number) => `${n}-vertex polygon`,
  puntoGeo: "Geolocated point",
  area: "Area",
  vereda: "Vereda",
  municipio: "Municipality",
  departamento: "Department",
  pais: "Country",
  sistema: "Production system",
  siembra: "Planting",
  tenencia: "Land tenure",
  infraTitulo: "Processing and facilities",
  aporte: "Contribution to the lot",
  escalaAltitud: "Farm altitude above sea level",
  productor: "Producer",
  historia: "The farm's story",
  caracteristicas: "What sets it apart",
  galeria: "Producer gallery",
  otrasFincas: "Other farms in the lot",
  visaTitulo: "Lot EUDR Visa",
  visaLead: "Due diligence under Regulation (EU) 2023/1115 lives at the farm. The lot inherits its Visa from the EUDR Passport of each farm of origin, with no paperwork of its own.",
  visaEstado: { eudr_ready: "Visa in force", pendiente: "Visa in progress", bloqueado: "Visa withheld", sin_origen: "No origin declared" },
  pasaporteEstado: { apta: "Passport in force", aprobada: "Approved, dossier not yet released", en_revision: "Under review by CTCx", pendiente: "In progress", rechazada: "Rejected", no_apta: "No Passport" },
  cadena: { finca: "Farm", fincaSub: "EUDR Passport", lote: "Lot", loteSub: "Inherited Visa", dds: "Export", ddsSub: "DDS statement", ue: "EU buyer", ueSub: "Checks the reference" },
  criteriosTitulo: "What the farm's Passport certifies",
  criterio: {
    deforestacion: "Deforestation-free after 31/12/2020",
    legal: "Produced in line with national law",
    tenencia: "Land tenure declared",
    geo: "Plot geolocation",
    ilegalidad: "No signs of illegality",
    documentos: "Documents available and verifiable",
    revision: "Dossier reviewed by CTCx",
  },
  geoPoligono: (n: number) => `${n}-vertex polygon`,
  geoPunto: "geolocated point",
  sinRemitir: "approved, not yet released",
  tenenciaLabel: { propietario: "Owner", poseedor: "Recognised possessor", asociacion: "Association" },
  estadoCriterio: { ok: "Met", pend: "Pending", stop: "Not met" },
  riesgoPais: "Country risk",
  riesgoPaisNota: "European Commission classification, Implementing Regulation (EU) 2025/1093.",
  dds: "Due diligence statement (DDS)",
  ddsVerificacion: "verification",
  sinDds: "The DDS is filed by the operator importing the coffee; its reference is recorded here once it exists.",
  sellos: "Seals covering the whole lot",
  verificado: "verified by CTCx",
  declarado: "declared",
  sinSellos: "No seal covers 100 % of the lot yet.",
  verVisa: "See the full EUDR Visa",
  verPasaporte: (n: string, c: string) => `See the EUDR Passport of ${n} (${c})`,
  geoTitulo: "Plot geolocation",
  geoLead: "WGS84 coordinates of the vertices of the declared polygon (Art. 9 of the Regulation). The EU operator uses them in its due diligence statement.",
  geoPuntoLead: "WGS84 coordinates of the plot's geolocated point (Art. 9 of the Regulation; a plot of up to 4 ha may be declared with a single point).",
  vertice: "Vertex",
  latitud: "Latitude",
  longitud: "Longitude",
  masVertices: (n: number) => `and ${n} more vertices in the farm's dossier`,
  gradoTitulo: "The Point and the Triad",
  gradoLead: "The CTCx grade combines cup quality (the Q-Grader's SCA Point) with three attributes of the lot: variety, process and recognition. Each attribute raises the multiplier according to its level C, B or A.",
  puntoCva: "CVA Point (SCA-104)",
  puntoSca2004: "SCA 2004 Point (worth the same in CVA)",
  multiplicador: "Multiplier",
  total: "CTCx points",
  triada: { variedad: "Variety", proceso: "Process", reconocimiento: "Recognition" },
  niveles: {
    variedad: { C: "Regional or traditional", B: "Specialty or hybrid", A: "Exotic or rare" },
    proceso: { C: "Washed", B: "Honey, natural, infused", A: "Experimental, fermentations" },
    reconocimiento: { C: "None", B: "1 to 3", A: "4 or more" },
  },
  composicion: "Declared varietal composition",
  escalaTitulo: "Where the lot sits on the CTCx scale",
  tituloTriada: "The lot's triad",
  imagenDefecto: "Farms and lots of backed origin, a CTCx illustration",
  variedadesTitulo: "The lot's varieties",
  variedadesFuente: "Profiles from the CTCx Variety Map",
  sinFichaVariedad: (n: string) => `The Variety Map has no profile yet for “${n}”.`,
  grupoGenetico: "Genetic group",
  origenVariedad: "Origin",
  altitudVariedad: "Altitude where it thrives",
  granoVariedad: "Bean",
  notasVariedad: "Typical cup notes",
  sinEvaluacion: "The lot does not yet have a Q-Grader evaluation governing its grade. This page is completed once CTCx confirms the Quality Centre report.",
  tazaTitulo: "Cup profile",
  tazaLead: "The Q-Grader's sheet that governs the grade: the affective assessment (how much each attribute pleases) and the descriptive one (what is perceived, where and how intensely).",
  afectiva: "Affective assessment",
  afectivaCva: "CVA · eight attributes on the 1 to 9 scale",
  afectivaSca: "SCA 2004 · ten attributes on the 6 to 10 scale",
  afectivaFicha: "Attributes reported in the lot's Ficha",
  escalaCva: "From 1 (extremely low) to 9 (extremely high). The dotted line is 5: neither high nor low.",
  radarCva: "Spider chart of the eight CVA attributes",
  puntoRige: "The Point that governs the grade",
  esElPunto: "It is the Point that governs the grade",
  tazasCva: (n: number, u: number, d: number) => `${n} cups · ${u} non-uniform · ${d} defective`,
  comparativo: (protocolo: string, v: string) => `${protocolo} cupped alongside: ${v}`,
  descriptiva: "Descriptive assessment",
  descriptivaLead: "Intensity from 0 to 15: low below 5, medium from 5 to 9.5, high from 10.",
  acidez: "Acidity",
  boca: "Mouthfeel",
  acidezTipo: { dulce: ["Sweet", "juicy, fruit-like, bright"], seca: ["Dry", "herby, grassy, tart"] },
  sinIntensidad: "No intensity",
  notasTitulo: "Notes on the flavour wheel",
  docPublico: "Public lot dossier",
  volverPortal: "Find my Lot",
  regionPie: "The lot's region. The farm's exact location is not published.",
  region: "Region",
  eudrListo: "EUDR ready: traceable to the farm, under Regulation (EU) 2023/1115.",
  avisoPublico: `Public file of the lot in the CTCx Public Catalogue. Produced by ${CTC_RAZON} from what the producer registered in Kaffetal Regal and what CTCx checked; what CTCx did not verify is not claimed. To buy it or request a sample, write to CTCx at ctcexport.com.`,
  tazas: "Cups",
  rueda: "Notes on the flavour wheel",
  ruedaFigura: "Where the notes fall on the wheel",
  ruedaFiguraNota: "Each note sits at its family's angle, further from the centre the more intense it is. Red outline: defect note.",
  intensidad: "intensity",
  defectoNota: "defect note",
  descriptivo: "Descriptive",
  perfil: "Cupper's profile",
  totalSca: "SCA 2004 total",
  fisicoTitulo: "Physical analysis",
  fisicoLead: "What happens to a parchment sample from hulling to sound green beans, and how the green coffee splits by screen size.",
  rendimiento: "Sample yield",
  pergamino: "Parchment",
  merma: "Hulling loss",
  verde: "Hulled green",
  defPrim: "Primary defects",
  defSec: "Secondary defects",
  sano: "Sound beans",
  factor: "Yield factor",
  factorNota: "kilos of parchment per 70 kg of sound green",
  humedad: "Green moisture",
  humedadRango: "export range 10 to 12 %",
  aw: "Water activity",
  densidad: "Density",
  defectuosa: "Defective beans",
  mallas: "Screen size",
  defectos: "Physical defects",
  defecto: "Defect",
  granos: "Beans",
  completos: "Full defects",
  noSabe: "Unknown",
  declaradoVsMedido: "Declared by the producer and measured in the lab",
  declarado2: "Declared",
  medido: "Measured",
  notasAnalisis: "Analysis notes",
  mejoraTitulo: "Improvement",
  respaldoHojaTitulo: "Evidence",
  anot: "Flavour Wheel improvement notes",
  anotLead: "The defect notes the Q-Grader marked and their most likely cause in processing. This is the first thing worth reviewing for the next harvest.",
  anotLimpio: "The flavour wheel marked no defect notes: the profile shows no process faults.",
  causa: "Likely cause",
  lecturaTitulo: "Reading the profile",
  lecturaFuente: "Written like the Coffee Wheel report, from the notes the Q-Grader marked.",
  conjeturasTitulo: "What the observations suggest",
  conjeturasLead: "Hypotheses drawn from what was measured and declared. They are starting points for the next harvest, not diagnoses.",
  evidencia: "From",
  areas: { taza: "Cup", fisico: "Physical", origen: "Origin" },
  respaldoTitulo: "Who stands behind each figure",
  respaldoLead: "Each block of this dossier and where it comes from. Filled: done. Dotted: pending. Dash: not applicable.",
  respaldoCols: ["Declared by the producer", "Reviewed by CTCx", "Measured by the Q-Grader"],
  respaldoFilas: { finca: "Farm, map and altitude", visa: "EUDR Visa", triada: "Variety, process and recognition", taza: "SCA Point and cup profile", fisico: "Physical analysis", grado: "CTCx grade", certs: "Certifications" },
  certs: "Farm certifications corroborated by CTCx",
  sinCerts: "No corroborated certification yet. Declared certifications without evidence are not printed.",
  esquema: "Scheme",
  numero: "No.",
  vigencia: "Validity",
  catalogo: "The lot's public page in the CTCx Public Catalogue",
  fuente: { q_grader_batch: "CTCx evaluation by Q-Grader", bcp_arena: "CTCx appraisal in the Arena", producer_claim: "Reported by the producer and checked by CTCx" },
  fechaAnalisis: "Analysis date",
  fichaFuente: { escaneo: "Producer documents transcribed by CTCx", productor: "Reported by the producer", ctc: "Transcribed by CTCx" },
  aviso: `This dossier is produced by ${CTC_RAZON} from the information the producer registered in Kaffetal Regal and what CTCx checked. What CTCx did not verify is not claimed.`,
  infra: {
    semillero: "Seedbed", tractor: "Tractor", acopio: "Storage", flotado: "Flotation tanks", lavado: "Washing", beneficio: "Specialised processing",
    fermentadores: "Anaerobic fermenters", patios: "Drying patios", marquesinas: "Drying tunnels", guardiolas: "Guardiola dryers", silos: "Drying silos",
    trilladora: "Huller", monitor_mallas: "Screen grader", optica: "Optical sorter", vacio: "Vacuum packing", tostadora: "Roaster",
    molino: "Grinder", empacadora_consumible: "Retail packing",
  },
  sistemaLabel: { sombra: "Shade-grown", agroforestal: "Agroforestry", tradicional: "Traditional, full sun" },
};

export const TEXTOS: Record<Lang, Textos> = { es: ES, en: EN };
export type { Textos };
